Public Enum EPresenterErgebnis
    ABBRECHEN
    ANMELDEN
    SPEICHERN
    BEENDEN
    EIGENEKURSE_ANZEIGEN
    MITGLIEDER_ANZEIGEN
    EIGENESPROFIL_ANZEIGEN
    SPORTART_ANZEIGEN
    TRAINER_ANZEIGEN
    MITARBEITER_ANZEIGEN
    TRAINER_ERSTELLEN
    KURS_ERSTELLEN
    MITGLIEDER_ERSTELLEN
    KURS_ANZEIGEN
    MITGLIEDER_EINZELN
    ABSAGEN
    SPORTART_EINZELN
    TRAINER_EINZELN
    MITARBEITER_ERSTELLEN
End Enum
