Public Enum EPresenterErgebnis
    ABBRECHEN
    ANMELDEN
    SPEICHERN
    LOESCHEN
    BEARBEITEN
    SCHLIESSEN
    ERSTELLEN
    ABSAGEN
    BEENDEN
    NEUESPORTART
    NEUERTRAINER
    NEUERKURS
    MEINKONTO
    ALLETRAINER
    ALLESCHUELER
    ALLEMITARBEITER
    NEUESCHUELER

End Enum
